# Generated by Django 5.2.7 on 2026-01-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_attributioncommande_alter_commande_etat_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='etat_commande',
            field=models.CharField(choices=[('en_cours', 'en_cours'), ('valide', 'valide'), ('livre', 'livre'), ('annule', 'annule')], default='en_cours', max_length=10),
        ),
    ]
