# Generated by Django 5.2.7 on 2026-01-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_commande_code_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='code_livraison',
            field=models.CharField(default='MARCHEPRO-', editable=False, max_length=20),
        ),
    ]
