# Generated by Django 5.2.7 on 2025-10-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='identifiant_vente',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
