# Generated by Django 5.2.7 on 2026-01-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_alter_detailvente_vente_alter_vente_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='identifiant_vente',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
