# Generated by Django 5.2.7 on 2026-01-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_alter_vente_identifiant_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='identifiant_vente',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
