# Generated by Django 5.2.7 on 2026-01-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0005_alter_vente_identifiant_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='client',
        ),
    ]
