# Generated by Django 5.2.7 on 2025-10-12 21:13

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_client', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom_client', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom client')),
                ('numero_telephone_client', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Veuillez entrer un numéro ivoirien valide (ex: +2250102030405 ou 0102030405).', regex='^(?:\\+225|00225)?(01|05|07|25|27)\\d{8}$')], verbose_name='Numero de téléphone')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
