# Generated by Django 5.2.7 on 2026-01-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_password_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(default='vendeur', editable=False, max_length=10, verbose_name='role utilisateur'),
        ),
    ]
