# Generated by Django 5.2.7 on 2026-01-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(default='client', editable=False, max_length=10, verbose_name='role utilisateur'),
        ),
    ]
