# Generated by Django 5.2.7 on 2026-01-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_client_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(default='client', editable=False, max_length=10, verbose_name='role client'),
        ),
    ]
