# Generated by Django 5.2.7 on 2026-01-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(blank=True, default='client', editable=False, max_length=10, null=True, verbose_name='role client'),
        ),
    ]
