# Generated by Django 5.2.7 on 2026-01-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
