# Generated by Django 5.2.7 on 2026-01-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_remove_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password_client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='photo_profil_client',
        ),
    ]
