# Generated by Django 5.2.7 on 2026-01-14 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_remove_client_password_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='numero_telephone_client',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Veuillez entrer un numéro ivoirien valide (ex: +2250102030405 ou 0102030405).', regex='^(?:\\+225|00225)?(01|05|07|25|27)\\d{8}$')], verbose_name='Numero de téléphone'),
        ),
    ]
