# Generated by Django 5.2.7 on 2026-01-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_alter_utilisateur_email_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('gerant', 'gerant'), ('vendeur', 'vendeur')], default='vendeur', max_length=10, verbose_name='role utilisateur'),
        ),
    ]
