# Generated by Django 5.2.7 on 2026-01-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='media/photo_profil_utilisateur/thumbnails/', verbose_name='Photo Profil Miniature'),
        ),
    ]
