# Generated by Django 5.2.7 on 2025-10-13 10:39

import django.db.models.deletion
import produits.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_categorie', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom_categorie', models.CharField(max_length=50, unique=True, verbose_name='nom catégorie')),
                ('description_categorie', models.TextField(blank=True, null=True, verbose_name='description produit')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_produit', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom_produit', models.CharField(max_length=50, unique=True)),
                ('image_produit', models.ImageField(blank=True, default=produits.models.image_produit_par_defaut, null=True, upload_to='media/image_produit/', verbose_name='Image du produit')),
                ('description_produit', models.TextField(blank=True, null=True, verbose_name='Description produit')),
                ('prix_unitaire_produit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire produit')),
                ('quantite_disponible_produit', models.IntegerField(verbose_name='quantite produit')),
                ('seuil_alerte_produit', models.IntegerField(verbose_name='Quantite alerte du produit')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.categorie', verbose_name='Categorie du produit')),
            ],
        ),
        migrations.CreateModel(
            name='AlertProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_alerte', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message_alerte', models.CharField(blank=True, max_length=50, null=True)),
                ('statut_alerte', models.BooleanField(default=False)),
                ('date_alerte', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit', verbose_name='alert_produit')),
            ],
        ),
    ]
