# Generated by Django 5.2.7 on 2026-01-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_alter_produit_quantite_produit_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertproduit',
            name='statut_alerte',
            field=models.BooleanField(default=True),
        ),
    ]
