# Generated by Django 5.2.7 on 2026-01-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_alter_alertproduit_statut_alerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='media/image_produit/thumbnails/', verbose_name='Miniature'),
        ),
    ]
