# Generated by Django 5.2.7 on 2026-01-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0009_produit_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='media/image_produit/thumbnails/', verbose_name='Image Produit Miniature'),
        ),
    ]
