# Generated by Django 5.2.7 on 2026-01-31 00:37

import cloudinary.models
import produits.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0011_alter_produit_image_produit_alter_produit_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image_produit',
            field=cloudinary.models.CloudinaryField(blank=True, default=produits.models.image_produit_par_defaut, max_length=255, null=True, verbose_name='image_produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, editable=False, max_length=255, null=True, verbose_name='thumbnail'),
        ),
    ]
