# Generated by Django 5.2.7 on 2026-01-31 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0013_produit_image_produit_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image_produit_url',
        ),
    ]
