# Generated by Django 5.2.7 on 2026-01-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0014_remove_produit_image_produit_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='thumbnail',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
